stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t pathnex-web-app .

test:
  stage: test
  script:
    - docker run pathnex-web-app npm test

deploy:
  stage: deploy
  script:
    - kubectl apply -f kubernetes/deployment.yaml
