pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t pathnex-web-app ./docker'
            }
        }

        stage('Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login docker.io \
                          -u "$DOCKER_USERNAME" \
                          --password-stdin

                        docker tag pathnex-web-app \
                          "$DOCKER_USERNAME/pathnex-web-app:latest"

                        docker push \
                          "$DOCKER_USERNAME/pathnex-web-app:latest"
                    '''
                }
            }
        }
    }
}
